package xyz.tbvns.rogue_block.client;

import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientEntityEvents;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.entity.event.v1.ServerPlayerEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents;
import net.kyori.adventure.audience.Audience;
import net.kyori.adventure.platform.fabric.FabricAudiences;
import net.kyori.adventure.platform.fabric.FabricClientAudiences;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.world.CreateWorldScreen;
import net.minecraft.world.gen.chunk.FlatChunkGenerator;
import net.minecraft.world.gen.chunk.FlatChunkGeneratorConfig;
import xyz.tbvns.rogue_block.client.Events.ClientTickEvent;

public class Rogue_blockClient implements ClientModInitializer {

    public static final FabricClientAudiences audiences =  FabricClientAudiences.builder().build();

    @Override
    public void onInitializeClient() {
        ClientTickEvents.START_WORLD_TICK.register(new ClientTickEvent());
    }
}
