package xyz.tbvns.rogue_block.Events;

import net.fabricmc.fabric.api.event.lifecycle.v1.ServerWorldEvents;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.world.ServerWorld;
import xyz.tbvns.rogue_block.Managers.WorldManager;

public class WorldLoadEvent implements ServerWorldEvents.Load{
    @Override
    public void onWorldLoad(MinecraftServer minecraftServer, ServerWorld serverWorld) {
        if (serverWorld == minecraftServer.getOverworld()) {
            serverWorld.setMobSpawnOptions(false);
        }
    }
}
